# 窗口设置 - 控制游戏窗口的基本属性
window:
  title: '我的沙盒游戏'    # 窗口标题
  width: 1024             # 窗口宽度（像素）
  height: 768             # 窗口高度（像素）

# 角色属性 - 定义角色的基本物理特征和初始状态
player:
  height: 3.0            # 角色高度（游戏单位）
  width: 1.0             # 角色宽度（游戏单位）
  depth: 1.0             # 角色深度（游戏单位）
  initial_position: [0, -10, 0]  # 初始位置 [x, y, z]
  initial_heading: 0     # 初始朝向角度（度数，0表示朝向Y轴正方向）

# 移动和物理属性 - 控制角色的运动表现
physics:
  acceleration: 50.0     # 移动加速度（单位/秒²）
  max_speed: 30.0       # 最大移动速度（单位/秒）
  deceleration: 0.95    # 减速系数（每帧速度衰减比例）
  min_speed: 0.01       # 最小速度阈值（低于此值速度归零）
  turn_speed: 120.0     # 转向速度（度/秒）
  gravity: -98         # 重力加速度（单位/秒²）
  ground_height: -1     # 地面高度（游戏单位）
  jump_speed: 30.5     # 跳跃初速度（单位/秒）
  jump_cooldown: 2.0000   # 跳跃冷却时间（秒）

# 相机控制 - 定义相机的行为和视角参数
camera:
  distance: 20.0        # 相机与角色的水平距离（游戏单位）
  height: 8.0          # 相机相对角色的高度（游戏单位）
  pitch: -20.0         # 相机俯视角度（度数，负值表示向下看）
  smooth: 0.95         # 相机跟随平滑系数（0-1，越大越平滑）
  mouse_sensitivity: 5.0  # 鼠标灵敏度（视角旋转速度）

# 光照设置 - 控制场景的光照效果
lighting:
  ambient:
    color: [0.4, 0.4, 0.4, 1.0]  # 环境光颜色 [R, G, B, A]
  directional:
    color: [0.8, 0.8, 0.8, 1.0]  # 定向光颜色 [R, G, B, A]
    direction: [45, -45, 0]       # 光源方向 [heading, pitch, roll]（度数）

# 地形设置 - 定义地形网格的外观
terrain:
  grid_size: 5          # 网格单元大小（游戏单位）
  size:
    x: [-50, 50]        # X轴范围 [最小值, 最大值]
    y: [-50, 50]        # Y轴范围 [最小值, 最大值]
  color: [0.1, 0.5, 0.1, 1.0]  # 地面颜色 [R, G, B, A]

# 方向指示器 - 角色前方的指示标记
direction_indicator:
  size: 0.3             # 指示器大小（游戏单位）
  color: [1.0, 0.0, 0.0, 1.0]  # 指示器颜色 [R, G, B, A]
  offset: [0, 1.3, 0]   # 相对角色的偏移位置 [x, y, z] 

# 碰撞设置
collision:
  player:
    radius: 0.5        # 角色碰撞体半径
    height_scale: 0.9  # 碰撞体高度缩放（相对于角色高度）
  debug:
    show_collisions: false  # 是否显示碰撞体（调试用） 

# 立方体运动设置
cube_movement:
  base_speed: 5.0         # 增加移动速度
  patrol_radius: 8.0      # 增加巡逻范围
  direction_change:
    min_interval: 2.0     # 增加方向改变间隔
    max_interval: 4.0
  rotation_speed: [-2, 2] # 增加旋转速度
  boundary: 45           # 活动范围边界 

# 参考立方体设置
reference_cubes:
  layout:
    x: [-50, 50]        # X轴范围 [最小值, 最大值]
    y: [-50, 50]        # Y轴范围 [最小值, 最大值]
    spacing: 10          # 立方体之间的间距
    safe_zone: 10        # 出生点安全区域范围（不生成立方体）
  appearance:
    scale: 1.0           # 立方体大小
    height: 1.0          # 立方体离地高度
    color_variation: true # 是否启用位置相关的颜色变化 

# 玩家状态设置
player_status:
  max_health: 100       # 最大生命值
  initial_health: 100   # 初始生命值
  health_bar:
    position: [-0.25, 0.9]  # 血条位置 [x, y]
    width: 0.5            # 血条宽度
    height: 0.08          # 血条高度
    colors:
      background: [0.2, 0.2, 0.2, 0.8]  # 血条背景色 [R, G, B, A]
      fill: [0.8, 0.2, 0.2, 1.0]        # 血条填充色 [R, G, B, A]
      border: [1.0, 1.0, 1.0, 0.8]      # 血条边框色 [R, G, B, A] 

# 游戏规则设置
game_rules:
  boundaries:
    x: [-45, 45]    # X轴边界范围 [最小值, 最大值]
    y: [-45, 45]    # Y轴边界范围 [最小值, 最大值]
    violation:
      count_time: 10.0  # 计数时间窗口（秒）
      max_violations: 2  # 最大违规次数
      safe_return_time: 15.0  # 安全返回时间（秒）
  damage:
    cube_collision: 10     # 碰撞伤害值
    out_of_bounds: 100    # 离开边界的伤害值
    warning_time: 5.0     # 警告时间（秒）
    invincible_time: 5.0  # 出生后的无敌时间（秒）
    damage_cooldown: 3.0  # 受伤后的无敌时间（秒）
  warning:
    text_scale: 0.2      # 警告文本大小
    text_color: [1, 0, 0, 1]  # 警告文本颜色 [R, G, B, A]
  game_over:
    text_position: [0, 0]  # 游戏结束文本位置
    text_scale: 0.15      # 游戏结束文本大小
  score:
    position: [1.3, 0.9]   # 得分显示位置
    scale: 0.05           # 得分文本大小 